<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <TransitivePackageReferencePinningEnabled>true</TransitivePackageReferencePinningEnabled>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="5.9.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="DotNext.Threading" Version="6.6.1" />
    <PackageVersion Include="Perfolizer" Version="0.7.5" />
    <PackageVersion Include="PolySharp" Version="1.16.0" />
    <PackageVersion Include="Pragmastat" Version="14.0.1" />
    <PackageVersion Include="Spectre.Console.Analyzer" Version="1.0.0" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageVersion Include="System.Diagnostics.PerformanceCounter" Version="10.0.11" />
    <PackageVersion Include="TUnit" Version="1.65.0" />
  </ItemGroup>
</Project>