<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>$(NoWarn);CA2007;CA1515</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNext.Threading" />
    <PackageReference Include="Perfolizer" />
    <PackageReference Include="Pragmastat" />
    <PackageReference Include="Spectre.Console.Analyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Spectre.Console.Cli" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppleDust.Shared\AppleDust.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AppleDust.Tests"
                        PublicKey="$(SnkPublicKey)" />
  </ItemGroup>

</Project>