<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <TargetFrameworks Condition="$(IsWindows)">$(TargetFrameworks);net48</TargetFrameworks>
    <NoWarn>$(NoWarn);CA2007;IDE0058</NoWarn>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Perfolizer" />
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AppleDust.Cli\AppleDust.Cli.csproj"
                      Condition="'$(TargetFramework)' == 'net10.0'" />
    <ProjectReference Include="..\..\src\AppleDust.Shared\AppleDust.Shared.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net10.0'">
    <Compile Remove="Cli\**" />
    <None Include="Cli\**" />
  </ItemGroup>

</Project>